### ISSUE TITLE
"real" ghidra module directions

### ISSUE THREAD

**Issue by therealchjones** [VDOO-Connected-Trust/ghidra-pyi-generator#12]
Thanks so much for your work on ghidra-pyi; the stubs work well for me in Visual Studio Code as well. I'm sorry if it sounds naive (that's because I'm naive), but [README.md](https://github.com/VDOO-Connected-Trust/ghidra-pyi-generator/blob/11446e6779acdbe5ff59d972cf39bac579aa042a/README.md) mentions "the real `ghidra` module" and "Import the Ghidra modules as usual", which I've been unable to locate.

Certainly `import ghidra` works within the ghidra script engine; outside, and referring to the "module", is this simply referring to the `Ghidra/Features/Base/src/main/java/ghidra/` tree? 

Again, my apologies for the naïveté, but I'd love to be better able to lint and debug more complex ghidra scripts, and if I can figure this out I'd be more than happy to submit some clarification for the README. Thanks again.

**Comment by tmr232** [comment]
Since the `ghidra` module is Java code, and not Python, it is not available outside of Ghidra. 
What the documentation is trying to express is that to get the type info, you don't need to change your code - you can keep using `import ghidra`, despite there being no such module in the environment your IDE is seeing. 

So there is no module to locate, outside of Ghidra, all you get is the stubs. I'm sorry for the confusion and hope this helps clear things up a bit. LMK if this helps or if you have more questions.
