### ISSUE TITLE
Build Failing with Ghidra 10.3 😢

### ISSUE THREAD

**Issue by clearbluejar** [VDOO-Connected-Trust/ghidra-pyi-generator#17]
https://github.com/VDOO-Connected-Trust/ghidra-pyi-generator/actions/runs/5003671445/jobs/8965205116

```console
Failed loading ghidra.util.BrowserLoader.BrowserRunner
WARN  Class interface ghidra.dbg.jdi.model.iface1.JdiModelSelectableObject is not annotated with @TargetObjectSchemaInfo (AnnotatedSchemaContext)  
Traceback (most recent call last):
  File "/home/runner/work/ghidra-pyi-generator/ghidra-pyi-generator/generate_ghidra_pyi.py", line 55, in <module>
    main()
  File "/home/runner/work/ghidra-pyi-generator/ghidra-pyi-generator/generate_ghidra_pyi.py", line 41, in main
    type_formatter.create_type_hints(pyi_root, ghidra_package)
  File "/home/runner/work/ghidra-pyi-generator/ghidra-pyi-generator/type_formatter.py", line 254, in create_type_hints
    write_package_classes(root, package_path, package)
  File "/home/runner/work/ghidra-pyi-generator/ghidra-pyi-generator/type_formatter.py", line 189, in write_package_classes
    pyi_content = format_pyi_class(cls)
  File "/home/runner/work/ghidra-pyi-generator/ghidra-pyi-generator/type_formatter.py", line 160, in format_pyi_class
    class_docs = '    """\n{}\n    """\n\n'.format(indent(cls.docstring))
UnicodeEncodeError: 'ascii' codec can't encode character u'\xb7' in position 292: ordinal not in range(128)
Error: Process completed with exit code 1.
``` 

Any ideas?

**Comment by tmr232** [comment]
Been quite a while since I looked at this code...
Looks like we're reading the docstrings without specifying an encoding ( https://github.com/VDOO-Connected-Trust/ghidra-pyi-generator/blob/ad01e1ec13bcfa0ea05a66e0b834b404e68adc65/helper.py#LL44C20-L44C20 ).
When we finally try to format them - we attempt to coerce them to ASCII but that fails.

I _think_ we can try and use a unicode string instead, and then explicitly save the file as UTF8.
But it's been a while since I did any Python 2.7...

**Comment by tmr232** [comment]
Another option would be to filter the non-ASCII chars out, but I think it's better to preserve docs as-is as much as possible.

I'll try and get to it - but I currently don't even have Ghidra on my machine...

**Comment by tmr232** [comment]
@fmagin wanna see if we can just convert this to Python 3, and run it on one of the tools that enable Python 3 for Ghidra?

The way I see it - the less Python 2 the better...

**Comment by fmagin** [comment]
I'm not sure how much I trust the various projects that allow Python 3 in Ghidra, haven't tried any of them yet. I don't remember how the stub generation worked, and if it involved some mechanisms that the Python3 integrations don't replicate accurately?

I'm kinda swamped with other stuff currently, my guess would be making this work for Python2 isn't that hard. @clearbluejar do you have time to look into this?

**Comment by clearbluejar** [comment]
I have quite a bit of experience with getting python 3 and Ghidra to work well, if that is the easier task. https://github.com/clearbluejar/ghidra-python-vscode-devcontainer-skeleton

It would simply be using a .devcontainer. I'm just not as familiar with what the package is actually doing, or how the generation works.

I can take the first step adding a devcontainer to the repo, which allow you to run the code in Python 3. The container includes the necessary Java and Ghidra already installed. It leverages `pyhidra`. Give me a thumbs up if this sounds reasonable and I will submit a PR.

**Comment by fmagin** [comment]
That sounds pretty good in theory.

One of my worries would be that the delay caused by breaking changes in Ghidra would cascade through the ecosystem. As far as I see `pyhidra` only got 10.3 support a few days ago, 2 weeks after the release. A project like the stubs here would only notice any other problem after `pyhidra` has ported, and then there is also the delay until someone working on it has time to fix it.

**Comment by tmr232** [comment]
That's a valid point, and a proper fix to the Python 2 code shouldn't be too hard (if I don't do it in the web IDE, that is :P )

Additionally - it seems we need to go over the classes tree in the docs (https://ghidra.re/ghidra_docs/api/overview-tree.html) and re-generate `classes.list` which seems to be woefully out of date.

**Comment by tmr232** [comment]
Let's see if I got it right now - https://github.com/VDOO-Connected-Trust/ghidra-pyi-generator/pull/18
